# Generated by Django 6.0.1 on 2026-04-13 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='KRACategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_standard', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kra_category',
            },
        ),
        migrations.CreateModel(
            name='KRACycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kra_cycle',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('min_experience', models.IntegerField(blank=True, null=True)),
                ('max_experience', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'level',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'rating',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stage',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('team', models.CharField(blank=True, max_length=255, null=True)),
                ('team_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_owner', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='kra_cycle.department')),
                ('manager', models.ForeignKey(blank=True, db_column='manager_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='kra_cycle.employee')),
                ('previous_manager', models.ForeignKey(blank=True, db_column='previous_manager_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_reports', to='kra_cycle.employee')),
                ('level', models.ForeignKey(blank=True, db_column='level_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='kra_cycle.level')),
                ('role', models.ForeignKey(blank=True, db_column='role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='kra_cycle.role')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='department_lead',
            field=models.ForeignKey(blank=True, db_column='department_lead_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_departments', to='kra_cycle.employee'),
        ),
        migrations.CreateModel(
            name='EmployeeKRACycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('is_date_based', models.BooleanField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kra_cycles', to='kra_cycle.employee')),
                ('employee_manager', models.ForeignKey(blank=True, db_column='employee_manager_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_kra_cycles', to='kra_cycle.employee')),
                ('kra_cycle', models.ForeignKey(blank=True, db_column='kra_cycle_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_cycles', to='kra_cycle.kracycle')),
                ('employee_level', models.ForeignKey(blank=True, db_column='employee_level', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_kra_cycles', to='kra_cycle.level')),
                ('stage', models.ForeignKey(blank=True, db_column='stage_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_kra_cycles', to='kra_cycle.stage')),
            ],
            options={
                'db_table': 'employee_kra_cycle',
            },
        ),
        migrations.CreateModel(
            name='KRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_standard', models.BooleanField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kras', to='kra_cycle.kracategory')),
            ],
            options={
                'db_table': 'kra',
            },
        ),
        migrations.CreateModel(
            name='EmployeeKRACycleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weightage', models.CharField(blank=True, max_length=10, null=True)),
                ('employee_kra_cycle', models.ForeignKey(blank=True, db_column='employee_kra_cycle_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='kra_cycle.employeekracycle')),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_cycle_categories', to='kra_cycle.kracategory')),
            ],
            options={
                'db_table': 'employee_kra_cycle_category',
            },
        ),
        migrations.CreateModel(
            name='KRALevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kra', models.ForeignKey(blank=True, db_column='kra_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kra_levels', to='kra_cycle.kra')),
                ('level', models.ForeignKey(blank=True, db_column='level_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kra_levels', to='kra_cycle.level')),
            ],
            options={
                'db_table': 'kra_level',
            },
        ),
        migrations.CreateModel(
            name='EmployeeKRALevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_by_lead', models.TextField(blank=True, null=True)),
                ('help_and_assistance_required', models.TextField(blank=True, null=True)),
                ('self_comment', models.TextField(blank=True, null=True)),
                ('lead_comment', models.TextField(blank=True, null=True)),
                ('progress_notes', models.TextField(blank=True, null=True)),
                ('lead_progress_notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kra_level_rows', to='kra_cycle.employee')),
                ('employee_kra_cycle', models.ForeignKey(blank=True, db_column='employee_kra_cycle_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kra_level_rows', to='kra_cycle.employeekracycle')),
                ('kra_level', models.ForeignKey(blank=True, db_column='kra_level_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_kra_levels', to='kra_cycle.kralevel')),
                ('lead_rating', models.ForeignKey(blank=True, db_column=' lead_rating_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_assessments', to='kra_cycle.rating')),
                ('self_rating', models.ForeignKey(blank=True, db_column='self_rating_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='self_assessments', to='kra_cycle.rating')),
            ],
            options={
                'db_table': 'employee_kra_level',
            },
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_roles', to='kra_cycle.employee')),
                ('role', models.ForeignKey(blank=True, db_column='role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_roles', to='kra_cycle.role')),
            ],
            options={
                'db_table': 'employee_role',
            },
        ),
        migrations.CreateModel(
            name='KRACycleStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('kra_cycle', models.ForeignKey(blank=True, db_column='kra_cycle_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cycle_stages', to='kra_cycle.kracycle')),
                ('stage', models.ForeignKey(blank=True, db_column='stage_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cycle_stages', to='kra_cycle.stage')),
            ],
            options={
                'db_table': 'kra_cycle_stage',
            },
        ),
        migrations.AddField(
            model_name='kracycle',
            name='stage',
            field=models.ForeignKey(blank=True, db_column='stage_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kra_cycles', to='kra_cycle.stage'),
        ),
    ]
