# Generated by Django 6.0.1 on 2026-04-13 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kra_cycle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kralevel',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kra_levels', to='kra_cycle.kracategory'),
        ),
        migrations.AddField(
            model_name='kralevel',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeekralevel',
            name='lead_rating',
            field=models.ForeignKey(blank=True, db_column='lead_rating_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_assessments', to='kra_cycle.rating'),
        ),
    ]
