# Generated by Django 6.0.1 on 2026-04-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kra_cycle', '0003_auditlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='changes',
            new_name='new_data',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='old_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
