# Generated by Django 6.0.1 on 2026-05-15 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kra_cycle', '0004_rename_changes_auditlog_new_data_auditlog_old_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeKRACycleStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employee_kra_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_overrides', to='kra_cycle.employeekracycle')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kra_cycle.stage')),
            ],
            options={
                'unique_together': {('employee_kra_cycle', 'stage')},
            },
        ),
    ]
