# Generated by Django 6.0.1 on 2026-05-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kra_cycle', '0005_employeekracyclestage'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeekracycle',
            name='is_stage_overridden',
            field=models.BooleanField(default=False),
        ),
    ]
