# Generated by Django 6.0.1 on 2026-05-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kra_cycle', '0006_employeekracycle_is_stage_overridden'),
    ]

    operations = [
        migrations.AddField(
            model_name='kracategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
