# Generated by Django 6.0.1 on 2026-05-20 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kra_cycle', '0007_kracategory_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kracategory',
            name='is_deleted',
        ),
    ]
