"""
Changes Role.id from auto-increment integer PK to a varchar PK,
and updates the two dependent FKs (Employee.role, EmployeeRole.role)
to match.

This is a manual migration (not autogenerated) because Postgres will not
let you change a PK's type while FK constraints depend on it. The SQL
below drops those constraints, converts all three columns, then
re-adds the constraints. Existing integer values are preserved as their
string form (e.g. 1 -> '1') — no renaming of values happens here.
"""

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kra_cycle', '0009_employeekracyclecategory_assigned_by_role_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE employee DROP CONSTRAINT IF EXISTS employee_role_f433297d_fk;
                ALTER TABLE employee_role DROP CONSTRAINT IF EXISTS employee_role_role_id_44429386_fk;

                ALTER TABLE role ALTER COLUMN id DROP IDENTITY IF EXISTS;
                ALTER TABLE role ALTER COLUMN id TYPE varchar(50) USING id::varchar;
                ALTER TABLE employee ALTER COLUMN role TYPE varchar(50) USING role::varchar;
                ALTER TABLE employee_role ALTER COLUMN role_id TYPE varchar(50) USING role_id::varchar;

                ALTER TABLE employee
                    ADD CONSTRAINT employee_role_f433297d_fk
                    FOREIGN KEY (role) REFERENCES role(id) ON DELETE SET NULL;

                ALTER TABLE employee_role
                    ADD CONSTRAINT employee_role_role_id_44429386_fk
                    FOREIGN KEY (role_id) REFERENCES role(id) ON DELETE SET NULL;
            """,
            reverse_sql="""
                ALTER TABLE employee DROP CONSTRAINT IF EXISTS employee_role_f433297d_fk;
                ALTER TABLE employee_role DROP CONSTRAINT IF EXISTS employee_role_role_id_44429386_fk;

                ALTER TABLE role ALTER COLUMN id TYPE integer USING id::integer;
                ALTER TABLE employee ALTER COLUMN role TYPE integer USING role::integer;
                ALTER TABLE employee_role ALTER COLUMN role_id TYPE integer USING role_id::integer;

                ALTER TABLE employee
                    ADD CONSTRAINT employee_role_f433297d_fk
                    FOREIGN KEY (role) REFERENCES role(id) ON DELETE SET NULL;

                ALTER TABLE employee_role
                    ADD CONSTRAINT employee_role_role_id_44429386_fk
                    FOREIGN KEY (role_id) REFERENCES role(id) ON DELETE SET NULL;
            """,
            state_operations=[
                migrations.AlterField(
                    model_name='role',
                    name='id',
                    field=models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='employee',
                    name='role',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='employees',
                        to='kra_cycle.role',
                        db_column='role',
                    ),
                ),
                migrations.AlterField(
                    model_name='employeerole',
                    name='role',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='employee_roles',
                        to='kra_cycle.role',
                        db_column='role_id',
                    ),
                ),
            ],
        ),
    ]