# Generated by Django 6.0.1 on 2026-06-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kra_cycle', '0010_role_id_to_varchar'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE employee DROP CONSTRAINT IF EXISTS employee_role_f433297d_fk;
                ALTER TABLE employee_role DROP CONSTRAINT IF EXISTS employee_role_role_id_44429386_fk;

                -- Convert columns back to integer
                ALTER TABLE role ALTER COLUMN id TYPE integer USING id::integer;
                ALTER TABLE employee ALTER COLUMN role TYPE integer USING role::integer;
                ALTER TABLE employee_role ALTER COLUMN role_id TYPE integer USING role_id::integer;

                -- Re-add identity generator for Role.id AutoField
                ALTER TABLE role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

                ALTER TABLE employee
                    ADD CONSTRAINT employee_role_f433297d_fk
                    FOREIGN KEY (role) REFERENCES role(id) ON DELETE SET NULL;

                ALTER TABLE employee_role
                    ADD CONSTRAINT employee_role_role_id_44429386_fk
                    FOREIGN KEY (role_id) REFERENCES role(id) ON DELETE SET NULL;
            """,
            reverse_sql="""
                ALTER TABLE employee DROP CONSTRAINT IF EXISTS employee_role_f433297d_fk;
                ALTER TABLE employee_role DROP CONSTRAINT IF EXISTS employee_role_role_id_44429386_fk;

                ALTER TABLE role ALTER COLUMN id DROP IDENTITY IF EXISTS;
                ALTER TABLE role ALTER COLUMN id TYPE varchar(50) USING id::varchar;
                ALTER TABLE employee ALTER COLUMN role TYPE varchar(50) USING role::varchar;
                ALTER TABLE employee_role ALTER COLUMN role_id TYPE varchar(50) USING role_id::varchar;

                ALTER TABLE employee
                    ADD CONSTRAINT employee_role_f433297d_fk
                    FOREIGN KEY (role) REFERENCES role(id) ON DELETE SET NULL;

                ALTER TABLE employee_role
                    ADD CONSTRAINT employee_role_role_id_44429386_fk
                    FOREIGN KEY (role_id) REFERENCES role(id) ON DELETE SET NULL;
            """,
            state_operations=[
                migrations.AlterField(
                    model_name='auditlog',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='department',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='employeekracycle',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='employeekracyclecategory',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='employeekracyclestage',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='employeekralevel',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='employeerole',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='kra',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='kracategory',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='kracycle',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='kracyclestage',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='kralevel',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='level',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='rating',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='role',
                    name='id',
                    field=models.AutoField(primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='stage',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
            ]
        ),
    ]
