# Generated by Django 6.0.1 on 2026-06-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kra_cycle', '0011_alter_auditlog_id_alter_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeekracycle',
            name='status',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='kracategory',
            name='description',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='kracategory',
            name='name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='kracycle',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='level',
            name='description',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='kracategory',
            table='category',
        ),
    ]
