// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/auth/sso/callback": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/cycles/:id": {
    params: {
      "id": string;
    };
  };
  "/assessments/self": {
    params: {};
  };
  "/cycles": {
    params: {};
  };
  "/kra-library": {
    params: {};
  };
  "/assignments": {
    params: {};
  };
  "/assessments/team": {
    params: {};
  };
  "/reports": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/login" | "/auth/sso/callback" | "/dashboard" | "/cycles/:id" | "/assessments/self" | "/cycles" | "/kra-library" | "/assignments" | "/assessments/team" | "/reports" | "/*";
  };
  "routes/home.jsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/public-layout.jsx": {
    id: "routes/public-layout";
    page: "/login" | "/auth/sso/callback";
  };
  "routes/login.jsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/sso-callback.jsx": {
    id: "routes/sso-callback";
    page: "/auth/sso/callback";
  };
  "routes/protected-layout.jsx": {
    id: "routes/protected-layout";
    page: "/dashboard" | "/cycles/:id" | "/assessments/self" | "/cycles" | "/kra-library" | "/assignments" | "/assessments/team" | "/reports";
  };
  "routes/dashboard.jsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/cycle-detail.jsx": {
    id: "routes/cycle-detail";
    page: "/cycles/:id";
  };
  "routes/self-assessment.jsx": {
    id: "routes/self-assessment";
    page: "/assessments/self";
  };
  "routes/role-layout.jsx": {
    id: "routes/role-layout";
    page: "/cycles" | "/kra-library" | "/assignments" | "/assessments/team" | "/reports";
  };
  "routes/cycles-list.jsx": {
    id: "routes/cycles-list";
    page: "/cycles";
  };
  "routes/kra-library.jsx": {
    id: "routes/kra-library";
    page: "/kra-library";
  };
  "routes/bulk-assignment.jsx": {
    id: "routes/bulk-assignment";
    page: "/assignments";
  };
  "routes/team-performance.jsx": {
    id: "routes/team-performance";
    page: "/assessments/team";
  };
  "routes/reports.jsx": {
    id: "routes/reports";
    page: "/reports";
  };
  "routes/catch-all.jsx": {
    id: "routes/catch-all";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.jsx");
  "routes/home": typeof import("./src/routes/home.jsx");
  "routes/public-layout": typeof import("./src/routes/public-layout.jsx");
  "routes/login": typeof import("./src/routes/login.jsx");
  "routes/sso-callback": typeof import("./src/routes/sso-callback.jsx");
  "routes/protected-layout": typeof import("./src/routes/protected-layout.jsx");
  "routes/dashboard": typeof import("./src/routes/dashboard.jsx");
  "routes/cycle-detail": typeof import("./src/routes/cycle-detail.jsx");
  "routes/self-assessment": typeof import("./src/routes/self-assessment.jsx");
  "routes/role-layout": typeof import("./src/routes/role-layout.jsx");
  "routes/cycles-list": typeof import("./src/routes/cycles-list.jsx");
  "routes/kra-library": typeof import("./src/routes/kra-library.jsx");
  "routes/bulk-assignment": typeof import("./src/routes/bulk-assignment.jsx");
  "routes/team-performance": typeof import("./src/routes/team-performance.jsx");
  "routes/reports": typeof import("./src/routes/reports.jsx");
  "routes/catch-all": typeof import("./src/routes/catch-all.jsx");
};